#pragma once

#define FPDFCLN_ERR_NOTINITIALIZE -2
#define FPDFCLN_ERR_FAIL -1
#define FPDFCLN_ERR_LIBNOTFIND -4
#define FPDFCLN_ERR_OK  0
#define FPDFCLN_ERR_NOTSUPPORT -3
#define FPDFCLN_ERR_INVALIDSEQUENCE -10